version: "3.8"

services:
  portfolio-web:
    build:
      dockerfile: Dockerfile
      context: .
    command: python manage.py runserver 0.0.0.0:8005
    volumes:
      - ./:/usr/src/app
    ports:
      - 8005:8005
    env_file:
      - ./.env
    depends_on:
      - portfolio-db
  portfolio-db:
    image: postgres:15.0-alpine
    volumes:
      - portfolio_postgres_data:/var/lib/postgresql/postgres_data
    env_file:
      - ./.db.env

volumes:
  portfolio_postgres_data: