version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: gunicorn portfolio.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    env_file:
      - ./prod.env
    volumes:
      - static_volume:/home/app/web/staticfiles
  nginx:
    build: ./nginx
    ports:
      - 80:80
    volumes:
      - static_volume:/home/app/web/staticfiles
    depends_on:
      - web

volumes:
  static_volume: