version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: gunicorn portfolio.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    env_file:
      - ./prod.env
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    depends_on:
      - db
  db:
    image: postgres:15.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/postgres_data
    env_file:
      - ./.db.env
    expose:
      - 5433
  nginx:
    build: ./nginx
    expose:
      - 80
    volumes:
      - static_volume:/home/app/web/staticfiles
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume:


networks:
  default:
    name: nginx-proxy
    external: true