version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: gunicorn portfolio.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    env_file:
      - ./prod.env
  nginx:
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - web