version: '3.8'

services:
  portfolio-web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: gunicorn portfolio.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    env_file:
      - ./prod.env
    volumes:
      - portfolio_static_volume:/home/app/web/staticfiles
      - portfolio_media_volume:/home/app/web/mediafiles
    depends_on:
      - portfolio-db
  portfolio-db:
    image: postgres:15.0-alpine
    volumes:
      - portfolio_postgres_data:/var/lib/postgresql/postgres_data
    env_file:
      - ./.db.env
  portfolio-nginx:
    build: ./nginx
    expose:
      - 80
    volumes:
      - portfolio_static_volume:/home/app/web/staticfiles
      - portfolio_media_volume:/home/app/web/mediafiles
    environment:
      - VIRTUAL_HOST=pawel-stawikowski.pl,www.pawel-stawikowski.pl
    depends_on:
      - portfolio-web

volumes:
  portfolio_postgres_data:
  portfolio_static_volume:
  portfolio_media_volume:


networks:
  default:
    name: nginx-proxy
    external: true
