# Generated by Django 4.1.2 on 2022-11-11 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_me', models.CharField(default='About me', max_length=50)),
                ('technologies', models.CharField(default='Technologies', max_length=50)),
                ('frameworks', models.CharField(default='Frameworks', max_length=50)),
                ('tools', models.CharField(default='Tools', max_length=50)),
                ('ides', models.CharField(default='IDEs', max_length=50)),
                ('operating_systems', models.CharField(default='Operating systems', max_length=50)),
                ('experience', models.CharField(default='Experience', max_length=50)),
                ('total_experience', models.CharField(default='Total experience', max_length=50)),
                ('current_employer', models.CharField(default='Current employer', max_length=50)),
                ('years', models.CharField(default='years', max_length=50)),
                ('latest_projects', models.CharField(default='Latest projects', max_length=50)),
                ('personal_projects', models.CharField(default='Personal projects', max_length=50)),
                ('see_more', models.CharField(default='See more', max_length=50)),
                ('work_experience', models.CharField(default='Work experience', max_length=50)),
                ('personal_info', models.CharField(default='Personal info', max_length=50)),
                ('download_cv', models.CharField(default='Download CV', max_length=50)),
                ('contact_form', models.CharField(default='Contact form', max_length=50)),
                ('skills', models.CharField(default='Skills', max_length=50)),
                ('education', models.CharField(default='Educations', max_length=50)),
                ('currently_studying', models.CharField(default='Currently studying', max_length=50)),
                ('credits', models.CharField(default='Credits', max_length=50)),
                ('select_language', models.CharField(default='Select language', max_length=50)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio_app.sitelanguage')),
            ],
        ),
    ]
