# Generated by Django 4.1.2 on 2022-11-11 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0003_translation_languages'),
    ]

    operations = [
        migrations.AddField(
            model_name='translation',
            name='year',
            field=models.CharField(default='year', max_length=30),
        ),
    ]
